version: '23'
services:
    sapperapp:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: sapperapp
        restart: always
        volumes:
          - ./app:/usr/src/app/
          - ./ecosystem.config.js/:/usr/src/app/ecosystem.config.js
        networks:
            - proxy
        expose:
            - "3000"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.sapperApp.entrypoints=https"
            - "traefik.http.routers.sapperApp.rule=Host(`wizardpalette.com`, `www.wizardpalette.com`)"
            - "traefik.http.services.sapperApp.loadbalancer.server.port=3000"
            - "traefik.docker.network=proxy"
  
networks:
    proxy:
        external: true