version: '2'
services:
    sapperApp:
        image: jbracho/pm2-sapper:1.0
        container_name: sapperApp
        restart: always
        volumes:
            - ./app/:/usr/src/app/sapperApp/
            - ./pm2-sapper/:/usr/src/app/
        networks:
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.sapperApp.entrypoints=https"
            - "traefik.http.routers.sapperApp.rule=Host(`example.com`, `www.example.com`)"
            - "traefik.http.services.sapperApp.loadbalancer.server.port=3000"
            - "traefik.docker.network=proxy"
  
networks:
    proxy:
        external: true